{% set org = "mrocklin" %}
{% set name = "streamz" %}
{% set version = "0.6.2" %}
{% set sha256 = "04446ece273c041506b1642bd3d8380367a8372196be4d6d6d03faafadc590b2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6
    - zict
    - tornado
    - toolz
    - setuptools
    - six

test:
  imports:
    - streamz
    - streamz.core

about:
  home: https://github.com/mrocklin/streamz/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Manage streaming data, optionally with Dask and Pandas

  description: |
    Manage streaming data, optionally with Dask and Pandas
  doc_url: https://streamz.readthedocs.io/en/latest/
  dev_url: https://github.com/mrocklin/streamz/

extra:
  recipe-maintainers:
    - CJ-Wright
    - mrocklin
    - jrmlhermitte
    - mariusvniekerk
    - martindurant
