{% set name = "streamz" %}
{% set version = "0.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d9ae5f4665c2a261950980c94dfa7f767507d2e33950651936c74b587cacaf22

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - tornado
    - toolz
    - zict

{% set deselect_tests = "" %}
# Unstable on CI due to timing problems.
{% set deselect_tests = " --deselect=test_core.py::test_partition_timeout_cancel" %}  # [osx]
{% set deselect_tests = deselect_tests + " --deselect=test_core.py::test_partition_timeout" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=test_core.py::test_timed_window" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=test_core.py::test_latest" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=test_core.py::test_partition_timeout" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=test_core.py::test_await_syntax" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=test_dask.py::test_map" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=test_dask.py::test_partition_then_scatter_async" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=test_dask.py::test_scan" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=test_dask.py::test_buffer" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=test_dask.py::test_buffer_sync" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=test_dask.py::test_starmap" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=test_sources.py::test_process_str" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=test_sources.py::test_from_iterable_backpressure" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=test_sources.py::test_from_iterable_stop" %}  # [win]

test:
  imports:
    - streamz
    - streamz.core
    - streamz.dataframe
    - streamz.batch
    - streamz.dask
    - streamz.sinks
    - streamz.sources
    - streamz.tests
    - streamz.utils_test
  requires:
    - pip
    - python
    - pytest
    - distributed
    - flaky
    - dask
    - numpy
    - pytest-asyncio
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest --pyargs streamz.tests {{ deselect_tests }}

about:
  home: https://github.com/python-streamz/streamz
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Real-time stream processing for python
  description: |
    Streamz helps you build pipelines to manage continuous streams of data. 
    It is simple to use in simple cases, but also supports complex pipelines
    that involve branching, joining, flow control, feedback, back pressure, and so on.
    Optionally, Streamz can also work with both Pandas and cuDF dataframes, 
    to provide sensible streaming operations on continuous tabular data.
  doc_url: https://streamz.readthedocs.io
  dev_url: https://github.com/python-streamz/streamz

extra:
  recipe-maintainers:
    - CJ-Wright
    - mrocklin
    - jrmlhermitte
    - mariusvniekerk
    - martindurant