travis:
  secure:
    BINSTAR_TOKEN: xyIjvrvY1rBDnOLAVSx+1zZa/jSvvD/eceiB7/VjcfD4osOPp2o5vZohhw2IZfsCnxX524ilindZRCERRhbsyndO3IhX9wLDZukgC7t5ZRK/6b0cb93XW2keyVJ1UxWDV85D1jXbmoQxoKlmv+9kB0gongsQMKrzPJWzfoRZGhEetRjwxR+BrnGEHpShIDuw8x4CBnAp1XHYPIsxLDTA6v6x/RKjLY0FQ8eymtC7Me+5CIeDZow6sBr9g7VwYN8R+aHUuavmYUhpj9KCboAU23HqJ8PLoekcRPGlPxF6iehrpvcm8x03+xun6Z0TXZVZMaw6KklzVJ04a9z9MaS+6XbHpKTfRL6GCUYKnzFoQPieGAZUT+mVFzfh+c7+0NpF5yP7OY+VR7zR+v+xK9vmM8Wpp/ThHZ9rTfAQHAnPuTmN0IxNidSInUM5Tq6j1nVKkhdes+URUaOwo8fmqtR5O/j1Rd9HbdeInhI67cYed6NNV88eVzh6UMnMKDsi2916M4V3DpSJWklsmrqpwgMTW4Vvw241ErbRH7RcLLIV/5ymq0lckc46deVVcuwn0MosrV8bOm6CmtFYbKNaaoAZwEm95DlIhVjfKM85BVtcJryWfVNYTf6dXiGBqccVIQloFrxA7v4e/6AtGdcV7v4ea6j8UzI8mzDD5UQAT6mdrQ8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
