travis:
  secure:
    BINSTAR_TOKEN: YUv2Azq5sxqqy+TEOrWZMxf5RLZQy/o5TZmldUSXcZmDUCAhwzHtHy3XU+l1wNEBo0bAgCcFi6/3LuKFmF5jV60oHuvLpBHcEOYaFXhcMMn1RTKZTxIxc5Yiu36K6K9WTg9HD0WQ0aoy7WsT0ZjthQFjsIdZjJOmztMUOoeBAkuXKXLHqh6XOEg0OnYMERFN8yJLE82DlCqP1CLpUSmp1k7OlQKEfVDu9siyb/VXsF7XBAEkbwQxqUpa31Vxo/p06Fnv4O9hZRxU0tLL0hInhh2YtxNyZG5dEURfjg5whN0Sj0ksIGe4Ei/lbtDMUuo2nhZrVc9UE957pzpYI+MC+O6zmHJlgrJS5m1sNXLfGmTx1bcR4zEqDfhC4a/mBqm4t55zL+cXQ1RJ82qxJoJQbgXG7PcgbHHiK5OyUgic1aKkWQOt+UOSz7zx0CxMdjgD9v0aWAfIP7I/v4rqw8Ivn4CFJ3eQx9ndfzvr7SWh2gkm+nPo2INapAb3e9JKUCY7na35kWB8aHY/wLl8WMl0iovkfA9CR2Wstlo/KWwYMMnPTX3jlMJpMWnJRz2vNlEr9T/1IJ8WqLs5nr6oUkxRedoFwcC+ULmhXb/EPRkyQgD1t1fJgAwsuRR6EcsQDrY0evOxvswmYlivVpqxt/3gPn8Je3BuZF7l2IgFJDFsRmw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
